MODE = "DEBUG"
BATCH_SIZE = 10

IMAGE_DIRECTORY = "Image"
CSV_DIRECTORY = "CSV"
CHECK_DIRECTORY = "Check"

REDIS_PORT = 6379
FLASK_PORT = 5000
SOCKET_PORT = 4444

#----- OPENVINO -----
MODEL_ROOT_DIR = "./model"
MODEL = "rbmodel.xml"
WEIGHTS = "rbmodel.bin"
DEVICE = "MYRIAD"

#----- IMAGES -----

IMAGE_HEIGHT = 244
IMAGE_WIDTH = 244
SCALE = 4
NUMBER_OF_ARGUMENTS = 8

